const SET_POKEMON = 'SET_POKEMON';
const SET_ERROR = 'SET_ERROR';
const CLEAR_ERROR = 'CLEAR_ERROR';
const FETCH_POKEMONS = 'FETCH_POKEMONS';

export { SET_POKEMON, SET_ERROR, CLEAR_ERROR, FETCH_POKEMONS };