const SET_POKEMON = 'SET_POKEMON';
const SET_ERROR = 'SET_ERROR';
const CLEAR_ERROR = 'CLEAR_ERROR';
const TOGGLE_LOADING = 'TOGGLE_LOADING';
const SET_FAVORITE = 'SET_FAVORITE';

export { SET_POKEMON, SET_ERROR, CLEAR_ERROR, TOGGLE_LOADING, SET_FAVORITE };